services:
  db:
    container_name: oracle-std-service-container
    image: container-registry.oracle.com/database/standard
    environment:
      DB_USER: oracledb
      DB_PASSWORD: oracledb
      DB_NAME: safepulse
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: safepulse-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin://db:5432/safepulse
      SPRING_DATASOURCE_USERNAME: oracledb
      SPRING_DATASOURCE_PASSWORD: oracledb
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: oracle.jdbc.OracleDriver
      SPRING_APPLICATION_NAME: safepulse
    ports:
      - "8080:8080"

volumes:
  pgdata:
